import time

from . import QuestionHandler

def type_writer_effect(text):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(0.003)  # Adjust the sleep time for the desired speed
    print()  # Move to the next line after the text is fully typed

def throne():
  type_writer_effect("Note: When you decide on a choice, write its number, don't write the choice.")
  type_writer_effect(" ")
  type_writer_effect("You are an angel, your duty is to protect the universe from the darkness.")
  type_writer_effect("You are one of the few creatures who are able to communicate with the universe.")
  type_writer_effect("your name is Seraphiel, the Guardian of realms.")
  type_writer_effect(" ")
  type_writer_effect("Are you brave enough to protect the realms?")
  print()
  type_writer_effect("1. Yes")
  type_writer_effect("2. No")
  print()
  response = QuestionHandler.question_response("Enter your choice: ","1","2")

  if response == "1":
    type_writer_effect(" ")
    type_writer_effect("You are in the celestial realm, doing your usual routine.")
    type_writer_effect("Suddenly, The universe shows you visions of the future about an incoming war.")
    type_writer_effect(" ")
    type_writer_effect("You: I have to do something to stop this war!. what should I do?")
    type_writer_effect(" ")
    type_writer_effect("1) Seek help from your friend.")
    type_writer_effect("2) Visit the library of heavens.")
    fv = QuestionHandler.question_response("Enter your choice: ","1","2")
    if fv == "1":
      type_writer_effect(" ")
      type_writer_effect("You go to look for your friend, Aurellius.")
      type_writer_effect("You enter Aurellius house, and you find him dead on the floor.")
      type_writer_effect(" ")
      type_writer_effect("You look around the house to find a clue, and you find a note from Aurellius.")
      type_writer_effect("You discover that the archangel Radiel has fallen to the darkness and became evil.")
      type_writer_effect("Radiel has used dark magic to control other angels and is planning to sacrifice a lot of creatures to ascend to godhood and control the universe.")
      type_writer_effect(" ")
      type_writer_effect("You go to fight Radiel and stop his evil plans")
      type_writer_effect(" ")
      type_writer_effect("On your way, you face hundreds of radiel minions")

      type_writer_effect("1) Fight them.")
      type_writer_effect("2) Run Away.")
      minfr = QuestionHandler.question_response("Enter your choice: ","1","2")
      if minfr == "1":
        type_writer_effect(" ")
        type_writer_effect("You fight the minions and defeat them, but you have been heavily injured.")
        type_writer_effect("Radiel shows up!!")
        type_writer_effect("You: I guess even the most righteous angels can't escape temptations")
        type_writer_effect("You: So, will you kill me now?.")
        type_writer_effect("Radiel: You are too powerful for me too control, so killing you is my only option.")
        type_writer_effect("Radiel attacks, but before you die, the universe casts some unkown magic on you.")
        type_writer_effect("Radiel cuts your head, You died")
        type_writer_effect(".....")
        type_writer_effect("But maybe that wasn't the end?")
      elif minfr == "2":
        type_writer_effect(" ")
        type_writer_effect("You run away from the minions, But eventually they catch up to you!.")
        type_writer_effect(" ")
        type_writer_effect("You fight the minions and defeat them, but you have been heavily injured.")
        type_writer_effect("Radiel shows up!!")
        type_writer_effect("You: I guess even the most righteous angels can't escape temptations")
        type_writer_effect("You: So, will you kill me now?.")
        type_writer_effect("Radiel: You are too powerful for me too control, so killing you is my only option.")
        type_writer_effect("Radiel attacks, but before you die, the universe casts some unkown magic on you.")
        type_writer_effect("Radiel cuts your head, You died")
        type_writer_effect(".....")
        type_writer_effect("But maybe that wasn't the end?")
    elif fv == "2":
      type_writer_effect(" ")
      type_writer_effect("You go to the library of heavens and search for a clue.")
      type_writer_effect("You didn't find anything in the library, so you go to ask for help from your friend.")
      type_writer_effect(" ")
      type_writer_effect("You go to look for your friend, Aurellius.")
      type_writer_effect("You enter Aurellius house, and you find him dead on the floor.")
      type_writer_effect(" ")
      type_writer_effect("You look around the house to find a clue, and you find a note from Aurellius.")
      type_writer_effect("You discover that the archangel Radiel has fallen to the darkness and became evil.")
      type_writer_effect("Radiel has used dark magic to control other angels and is planning to sacrifice a lot of creatures to ascend to godhood and control the universe.")
      type_writer_effect(" ")
      type_writer_effect("You go to fight Radiel and stop his evil plans")
      type_writer_effect(" ")
      type_writer_effect("On your way, you face hundreds of radiel minions")

      type_writer_effect("1) Fight them.")
      type_writer_effect("2) Run Away.")
      minfr = QuestionHandler.question_response("Enter your choice: ","1","2")
      if minfr == "1":
        type_writer_effect(" ")
        type_writer_effect("You fight the minions and defeat them, but you have been heavily injured.")
        type_writer_effect("Radiel shows up!!")
        type_writer_effect("You: I guess even the most righteous angels can't escape temptations")
        type_writer_effect("You: So, will you kill me now?.")
        type_writer_effect("Radiel: You are too powerful for me too control, so killing you is my only option.")
        type_writer_effect("Radiel attacks, but before you die, the universe casts some unkown magic on you.")
        type_writer_effect("Radiel cuts your head, You died")
        type_writer_effect(".....")
        type_writer_effect("But maybe that wasn't the end?")
      elif minfr == "2":
        type_writer_effect(" ")
        type_writer_effect("You run away from the minions, But eventually they catch up to you!.")
        type_writer_effect(" ")
        type_writer_effect("You fight the minions and defeat them, but you have been heavily injured.")
        type_writer_effect("Radiel shows up!!")
        type_writer_effect("You: I guess even the most righteous angels can't escape temptations")
        type_writer_effect("You: So, will you kill me now?.")
        type_writer_effect("Radiel: You are too powerful for me too control, so killing you is my only option.")
        type_writer_effect("Radiel attacks, but before you die, the universe casts some unkown magic on you.")
        type_writer_effect("Radiel cuts your head, You died")
        type_writer_effect(".....")
        type_writer_effect("But maybe that wasn't the end?")

    type_writer_effect(" ")
    type_writer_effect(" ")
    type_writer_effect("You open your eyes, and realize you have reincarnated into a human body!")
    type_writer_effect("You: I guess that was the magic of the universe!")
    type_writer_effect("You are imprisoned in a cursed castle that is filled with monsters and ruled by lich.")
    type_writer_effect("You can feel that your angelic power is in the castle, there are 4 fragments.")
    type_writer_effect("You manage to escape from the prsion and go to find the fragments.")
    type_writer_effect("On your way to collect the fragments, you face some insect monsters.")
    type_writer_effect(" ")
    type_writer_effect("1) Sneak around them")
    type_writer_effect("2) Fight them")
    type_writer_effect(" ")
    sof = QuestionHandler.question_response("what will you do? : ","1","2")

    if sof == "1":
      type_writer_effect(" ")
      type_writer_effect("The minions were busy eating someone, and they didn't notice you.")
      type_writer_effect("You suceed in sneaking around them.")
      type_writer_effect(" ")
      type_writer_effect("You go looking for the fragments of your angelic power")
      type_writer_effect("You see a monster, but it hasn't noticed you.")
      type_writer_effect(" ")
      type_writer_effect("1) Fight it")
      type_writer_effect("2) Sneak around it")
      fos = QuestionHandler.question_response("what will you do? : ","1","2")

      if fos == "1":
        type_writer_effect(" ")
        type_writer_effect("You fight the monster, but you lose.")
        type_writer_effect("The monster starts to tear you piece by piece.")
        type_writer_effect("When you are on the verge of death, the monster lights you on fire.")
        type_writer_effect("You scream in pain as you are burning slowly till you die")
        type_writer_effect("You were unarmed, what did you expect?")
        type_writer_effect("Game Over.")

      elif fos == "2":
        type_writer_effect(" ")
        type_writer_effect("You sneak aroud the monster succesfully.")
        type_writer_effect("That was a smart decesion, after all you were unarmed.")
        type_writer_effect(" ")
        type_writer_effect("you continue on your way until you find The fragment, it's inside a sword")
        type_writer_effect("You pick the sword, but to restore your powers, you have to collect the other fragments.")
        type_writer_effect("The fragment inside the sword allows you to use some magic.")
        type_writer_effect("Untill you restore your power, you You can use the sword to fight and cast magic.")
        type_writer_effect("You leave the room to continue your journey.")
        type_writer_effect("On your way out, you encounter a monster.")
        type_writer_effect(" ")
        type_writer_effect("1) Fight it")
        type_writer_effect("2) Run away")
        type_writer_effect(" ")
        rof = QuestionHandler.question_response("what will you do? : ","1","2")

        if rof == "1":
          type_writer_effect("You fight the monster and kill it")
          type_writer_effect("You notice that the monster was holding something.")
          type_writer_effect("You: What's that?.")
          type_writer_effect("You pick it up")
          type_writer_effect("It's a bitten human hand")
          type_writer_effect("You: ....., eww!")
          type_writer_effect("You throw it on the ground.")
          type_writer_effect("You move on your way.")
          type_writer_effect(" ")

        elif rof == "2":
          type_writer_effect(" ")
          type_writer_effect("You run away from the monster and move on your way.")
        type_writer_effect("While you are walking, you hear someone screaming.")
        type_writer_effect(" ")
        type_writer_effect("You: What was that?!")
        type_writer_effect("You: Let me go and check.")
        type_writer_effect("You see a girl surrounded by monsters. What will you do?")
        type_writer_effect(" ")
        type_writer_effect("1) Help her")
        type_writer_effect("2) Move on your way!")
        hom = QuestionHandler.question_response("what will you do? : ","1","2")
        if hom == "1":
          type_writer_effect("You defeat the monsters and save the girl.")
          type_writer_effect("Girl: Thank you so much!") 
          type_writer_effect("Girl: I have to go now, but let me advice you this.")
          type_writer_effect(" There is a monster called Decalius, he has an anti magic armour, so magic doesn't affect him.")

        elif hom == "2":
          type_writer_effect("You: That's not my problem.")
          type_writer_effect("You continue on your way.")
        type_writer_effect(" ")
        type_writer_effect("As you move towards the fragment, you encounter Decalius, the Knight of Unhallowed Blood!!!")
        type_writer_effect("You enter the fight.")
        type_writer_effect(" ")
        type_writer_effect("1) Fight using your sword.")
        type_writer_effect("2) Fight using your magic.")
        fsm = QuestionHandler.question_response("what will you do? : ","1","2")
        if fsm == "1":
          type_writer_effect("")
          type_writer_effect("You attack decalius with your sword.")
          type_writer_effect("You defeat Decalius, and you take his anti magic armor.")
          type_writer_effect("You continue on your way.")
          type_writer_effect("You reach the place of the second fragment, and you encounter Eurika, the ghost of Black blood!!")
          type_writer_effect("Defeat Eurika to take the fragment")
          type_writer_effect(" ")
          type_writer_effect("1) Fight using your sword.")
          type_writer_effect("2) Fight using your magic.")       
          eur = QuestionHandler.question_response("what will you do? : ","1","2")
          if eur == "1":
            type_writer_effect(" ")
            type_writer_effect("You attack Eurika with your sword, your attack passes through her body.")
            type_writer_effect("Eurika attacks with magic, but she fails because of your armour.")
            type_writer_effect("Eurika screams loudly, you start bleading from your ears.")
            type_writer_effect("You died.")
            type_writer_effect("How stupid do you have to be to fight a ghost using a sword?")
            type_writer_effect("Game Over.")
          elif eur == "2":
            type_writer_effect(" ")
            type_writer_effect("You attack Eurika with your magic.")
            type_writer_effect("You defeated Eurika, and got the second fragment.")
            type_writer_effect("The last two fragments are in the lich's room, so you go there.")
            type_writer_effect("You enter the lich's room, but the lich is not there.")
            type_writer_effect("You see a wierd ring on a table inside the room.")
            type_writer_effect("If you wear it, you will gain dark magic, but that can be dangerous")
            type_writer_effect(" ")
            type_writer_effect("1) Wear the ring.")
            type_writer_effect("2) destroy the ring.")
            gob = QuestionHandler.question_response("what will you do? : ","1","2")
            if gob == "1":#(pick ring)/ gain dark magic
                type_writer_effect("You pick up the ring.")
                type_writer_effect("You gain Dark magic, But you have been corrupted")
                type_writer_effect("The lich notices your magic, and attacks you with his magic.")
                type_writer_effect(" ")
                type_writer_effect("1) Defend using your magic.")
                type_writer_effect("2) Charge at him and attack.")
                flich = QuestionHandler.question_response("what will you do? : ","1","2")
                if flich == "1":
                  type_writer_effect(" ") 
                  type_writer_effect("You use magic to bounce his attack, you succeed.")
                  type_writer_effect("The lich uses magic to throw stone at you.")
                  type_writer_effect("You died, crushed by stones.")
                  type_writer_effect("Like a little bug")
                  type_writer_effect("Game Over.")
                elif flich == "2":
                    type_writer_effect(" ")
                    type_writer_effect("You charge at the lich, his magic fails because of your armour.")
                    type_writer_effect("Your attack succeed.")
                    type_writer_effect(" ")
                    type_writer_effect("The lich is still affected by your attack, you have chance to send a final attack.")
                    type_writer_effect("The lich is too strong, you have to sacrifice something to activate a powerful magic to kill him.")
                    type_writer_effect(" ")
                    type_writer_effect("1) sacrifice the prisoners to attack.")
                    type_writer_effect("2) sacrifice Your dark magic to attack.")
                    flich2 = QuestionHandler.question_response("what will you do? : ","1","2")
                    type_writer_effect(" ")
                    if flich2 == "1":
                      type_writer_effect(" ")
                      type_writer_effect("You sacrifice prisoners to activate a powerful dark magic.")
                      type_writer_effect("Your attacks succeed, the lich dies.")
                      type_writer_effect("You defeated the lich, but the dark magic inside grew stronger and made you evil.")
                      type_writer_effect(".........")
                      type_writer_effect("You collect the other two fragments and try to restore your power.")
                      type_writer_effect("Your powers rejects you because you became evil.")
                      type_writer_effect("You are unable to restore your power and ascend celestial.")
                      type_writer_effect("You use your dark magic to ascend to the celestial realm.")
                      type_writer_effect("You can't take your equipment with you.")

                      type_writer_effect(" ")
                      type_writer_effect(" ")
                      type_writer_effect("You are now in the celestial realm.")
                      type_writer_effect("You are heading towards the archangel to defeat him")
                      type_writer_effect("But Your goal has changed?!!.")
                      type_writer_effect(" ")
                      type_writer_effect("On your way, You encounter some mindcontrolled angels.")
                      type_writer_effect(" ")
                      type_writer_effect("1) Convince them to join your side.")
                      type_writer_effect("2) Use your dark magic to control them.")
                      darka = QuestionHandler.question_response("what will you do? : ","1","2")
                      if darka == "1":
                        type_writer_effect(" ")
                        type_writer_effect("You: Join my side and fight Radiel with me.")
                        type_writer_effect("Angels: Why should we join you?")
                        type_writer_effect("You convince them to join your side, by promising to give them power.")
                        type_writer_effect("The angels pretend to join your side.")
                        type_writer_effect("But after a while, They attack you from behind!!")
                        type_writer_effect("They kept on stabing you until you died.")
                        type_writer_effect("they were still being controlled by Radiel.")
                        type_writer_effect("And you believed they were on your side!!")
                        type_writer_effect("What an idiot, easily manipulated, pathetic pawn.")
                        type_writer_effect("Game Over.")
                      elif darka == "2":
                        type_writer_effect(" ")
                        type_writer_effect("You use your dark magic to control them.")
                        type_writer_effect("The angels will obey you instead of radiel.")
                        type_writer_effect(" ")
                        type_writer_effect("You move towards Radiel, and on Your way you control other angels.")
                        type_writer_effect(" ")
                        type_writer_effect("After a while, You reached Radiel.")
                        type_writer_effect("Radiel: Guess you we are not that different after all.")
                        type_writer_effect("You: The only difference between us is that I will win and you will die.")
                        type_writer_effect("Radiel attacks you with dark energy")
                        type_writer_effect(" ")
                        type_writer_effect("1) Absorb the dark energy.")
                        type_writer_effect("2)Reflect his attack.")

                        darch = QuestionHandler.question_response("what will you do? : ","1","2")
                        if darch == "1":
                          type_writer_effect(" ")
                          type_writer_effect("You try to absorb the dark energy, but you fail.")
                          type_writer_effect("You get heavily injured.")
                          type_writer_effect("Radiel attacks you again.")
                          type_writer_effect("You have fallen down and are unable to move!!")
                          type_writer_effect("Radiel attacks you, he stabs you in the eyes.")
                          type_writer_effect("You scream in pain while Radiel is laughing at you.")
                          type_writer_effect("You die.")
                          type_writer_effect("Game Over.")

                        elif darch == "2":
                          type_writer_effect(" ")
                          type_writer_effect("You use you magic to reflect the dark energy, you succeed")
                          type_writer_effect("You attack Radiel and fight him for a while.")
                          type_writer_effect("Radiel gets injured, so he starts to perform his final attack.")
                          type_writer_effect(" ")
                          type_writer_effect("You have two choices.")
                          type_writer_effect("1) Use both of your dark magic and angelic powers to attack him.")
                          type_writer_effect("2) Sacrifice nearby angels to activate a powerful dark magic.")
                          darch2d = QuestionHandler.question_response("what will you do? : ","1","2")
                          if darch2d == "1":
                            type_writer_effect(" ")
                            type_writer_effect(" You mix your dark magic with your angelic powers to attack Radiel.")
                            type_writer_effect("Your attack is more powerful than Radiel's attack.")
                            type_writer_effect("You defeat Radiel.")
                            type_writer_effect(" ")
                            type_writer_effect(".....")     
                            type_writer_effect("But mixing two opposite powers was a bad idea.")
                            type_writer_effect("You: What's happeneing?")
                            type_writer_effect("The dark magic and Your angelic powers are too powerful, They are fighting inside of you.")
                            type_writer_effect("Unable to handle these powers, You start to feel agonizing pain.")
                            type_writer_effect("You body is being torn from the inside as you scream in pain.")
                            type_writer_effect("As your consciousness is fading, You wonder if have lost yourself in your journey.")
                            type_writer_effect("You: ...D-Did I....")
                            type_writer_effect("You: Did I choose the wrong path?")
                            type_writer_effect(".......")
                            type_writer_effect("You died.")
                            type_writer_effect(" ")
                            type_writer_effect(" ")
                            type_writer_effect("THE END.")

                          elif darch2d == "2":
                            type_writer_effect(" ")
                            type_writer_effect("You sarifice nearby angels to activite a powerful dark magic.")
                            type_writer_effect("Your attacks succeed, Radiel falls down.")
                            type_writer_effect("You absorb Radiel's power while he screams in pain.")
                            type_writer_effect("Radiel dies!")
                            type_writer_effect(" ")
                            type_writer_effect("Instead of protecting the realms, you use your dark magic to ascend to godhood!!")
                            type_writer_effect("You win in the end, but you have lost yourself to the darkness.")
                            type_writer_effect(" ")
                            type_writer_effect(" ")
                            type_writer_effect("THE END.")


                    elif flich2 == "2":
                      type_writer_effect(" ")
                      type_writer_effect("You sacrifice your dark magic to activate a powerful spell")
                      type_writer_effect("Your attacks succeed, the lich dies.")
                      type_writer_effect(" ")
                      type_writer_effect("You collect all the fragments and restore your angelic powers")
                      type_writer_effect(" ")
                      type_writer_effect(" ")
                      type_writer_effect("You ascend to the celestial realm.")
                      type_writer_effect("To fight Radiel and his followers, the universe gives you the power to purify the evil.")
                      type_writer_effect("Now, you can bring the corrupted angels back to their nature.")
                      type_writer_effect("But, you have to weaken them first.")
                      type_writer_effect(" ")
                      type_writer_effect("You move toward Radiel.")
                      type_writer_effect("On your way, you face corrupted angels")
                      type_writer_effect(" ")
                      type_writer_effect("1) Offer to help them and purify the dark in them.")
                      type_writer_effect("2) Fight them, then purify them.")

                      gway = QuestionHandler.question_response("what will you do? : ","1","2")
                      if gway == "1":
                        type_writer_effect(" ")
                        type_writer_effect("They accept your offer.")
                        type_writer_effect("You start to purify them.")
                        type_writer_effect("But they take this chance to attack and stabbed you.")
                        type_writer_effect("They watched you as you bled slowly to your death.")
                        type_writer_effect("You died.")
                        type_writer_effect("Game Over.")
                      elif gway == "2":
                        type_writer_effect(" ")
                        type_writer_effect("You fight them and win.")
                        type_writer_effect("You start to purify them.")
                        type_writer_effect("They are purified, and they will join your side.")
                        type_writer_effect(" ")
                        type_writer_effect("On your way to Radiel, you purify other angels.")
                        type_writer_effect(" ")
                        type_writer_effect("You reach Radiel.")
                        type_writer_effect(" ")
                        type_writer_effect("Radiel: LOOK AT YOU, back from the dead!!!")
                        type_writer_effect("You: I wish I could save you, but you reached the point of no return.")
                        type_writer_effect("You: it's your turn to die now.")
                        type_writer_effect(" ")
                        type_writer_effect("Radiel attacks you using dark energy.")
                        type_writer_effect(" ")
                        type_writer_effect("1) Defend the attack with the other angels.")
                        type_writer_effect("2) Use your powers to purify Radiel.")
                        garch = QuestionHandler.question_response("what will you do? : ","1","2")
                        if garch == "1":
                          type_writer_effect(" ")
                          type_writer_effect("You succeed in defending the attack.")
                          type_writer_effect("After a fierce battle, Radiel uses his final attack to kill you and the angels!!")
                          type_writer_effect(" ")
                          type_writer_effect("1) Perform a combined attack.")
                          type_writer_effect("2) Sacrifice yourself to defeat Radiel and protect everyone.")
                          garch2 = QuestionHandler.question_response("what will you do? : ","1","2")
                          if garch2 == "1":
                            type_writer_effect(" ")    
                            type_writer_effect("You gather all of your power to attack.")
                            type_writer_effect("The other angels give you their powers.")
                            type_writer_effect("You use that power to attack Radiel.")
                            type_writer_effect("Radiel falls down.")
                            type_writer_effect(" ")
                            type_writer_effect("Radiel: Maybe I shouldn't have fallen to the temptations of The darkness.")
                            type_writer_effect("Radiel dies.")
                            type_writer_effect("You have protected the Universe!!!")
                            type_writer_effect("Congragulations!!!")
                            type_writer_effect(" ")
                            type_writer_effect(" ")
                            type_writer_effect("THE END!!!.")

                          elif garch2 == "2":
                            type_writer_effect(" ")
                            type_writer_effect("You charge at Radiel and try to divert the dircetion of his attack away from the other angels.")
                            type_writer_effect("You succeed.")
                            type_writer_effect("The effect of the attack kills Radiel!!")
                            type_writer_effect("But, You also die because you were near the attack!!!")
                            type_writer_effect("You defeated Radiel and protected the universe, but it costed you your life.")
                            type_writer_effect("You will be remmembered as a hero who saved the universe.")
                            type_writer_effect(" ")
                            type_writer_effect(" ")
                            type_writer_effect("THE END!!!.")


            elif gob == "2":
                type_writer_effect("You destroy the ring by throwing it into the lava.")
                type_writer_effect("You look around and you find the lich, he hasn't noticed you yet.")
                type_writer_effect(" ")
                type_writer_effect("1) Attack him.")
                type_writer_effect("2) search for the other fragment to become stronger.")
                nrlich = QuestionHandler.question_response("what will you do? : ","1","2")
                if nrlich == "1":
                  type_writer_effect(" ")
                  type_writer_effect("You attack the lich, and succeed.")
                  type_writer_effect("Before you do anything else, the lich minions attack you")
                  type_writer_effect("They pierce you with their spears until you die.")
                  type_writer_effect("Game Over.")
                elif nrlich == "2":
                  type_writer_effect(" ")
                  type_writer_effect("You find the other fragment, your magic is stronger now.")
                  type_writer_effect("The lich notices you and attacks you.")
                  type_writer_effect(" ")
                  type_writer_effect("1) Dodge his attack, and prepare your attack.")
                  type_writer_effect("2) Charge at the lich and attack him.")
                  nrlich2 = QuestionHandler.question_response("what will you do? : ","1","2")
                  if nrlich2 == "1":
                    type_writer_effect(" ")
                    type_writer_effect("You dodge the lich attack, and prepare your attack.")
                    type_writer_effect("But before you are done, the lich attacks you again and pushes you into the lava pool.")
                    type_writer_effect("You died while burning slowly.")
                    type_writer_effect("Game Over.")
                  elif nrlich2 == "2":
                    type_writer_effect(" ")
                    type_writer_effect("the lich uses his magic to attack, but fails because of your armour.")
                    type_writer_effect("You charge at him and attack again, you succeed.")
                    type_writer_effect("The lich Dies.")
                    type_writer_effect(" ")
                    type_writer_effect("You collect all the fragments and restore your angelic powers")
                    type_writer_effect(" ")
                    type_writer_effect(" ")
                    type_writer_effect("You ascend to the celestial realm.")
                    type_writer_effect("To fight Radiel and his followers, the universe gives you the power to purify the evil.")
                    type_writer_effect("Now, you can bring the corrupted angels back to their nature.")
                    type_writer_effect("But, you have to weaken them first.")
                    type_writer_effect(" ")
                    type_writer_effect("You move toward Radiel.")
                    type_writer_effect("On your way, you face corrupted angels")
                    type_writer_effect(" ")
                    type_writer_effect("1) Offer to help them and purify the dark in them.")
                    type_writer_effect("2) Fight them, then purify them.")

                    gway = QuestionHandler.question_response("what will you do? : ","1","2")
                    if gway == "1":
                      type_writer_effect(" ")
                      type_writer_effect("They accept your offer.")
                      type_writer_effect("You start to purify them.")
                      type_writer_effect("But they take this chance to attack and stabbed you.")
                      type_writer_effect("They watched you as you bled slowly to your death.")
                      type_writer_effect("You died.")
                      type_writer_effect("Game Over.")
                    elif gway == "2":
                      type_writer_effect(" ")
                      type_writer_effect("You fight them and win.")
                      type_writer_effect("You start to purify them.")
                      type_writer_effect("They are purified, and they will join your side.")
                      type_writer_effect(" ")
                      type_writer_effect("On your way to Radiel, you purify other angels.")
                      type_writer_effect(" ")
                      type_writer_effect("You reach Radiel.")
                      type_writer_effect(" ")
                      type_writer_effect("Radiel: LOOK AT YOU, back from the dead!!!")
                      type_writer_effect("You: I wish I could save you, but you reached the point of no return.")
                      type_writer_effect("You: it's your turn to die now.")
                      type_writer_effect(" ")
                      type_writer_effect("Radiel attacks you using dark energy.")
                      type_writer_effect(" ")
                      type_writer_effect("1) Defend the attack with the other angels.")
                      type_writer_effect("2) Use your powers to purify Radiel.")
                      garch = QuestionHandler.question_response("what will you do? : ","1","2")
                      if garch == "1":
                        type_writer_effect(" ")
                        type_writer_effect("You succeed in defending the attack.")
                        type_writer_effect("After a fierce battle, Radiel uses his final attack to kill you and the angels!!")
                        type_writer_effect(" ")
                        type_writer_effect("1) Perform a combined attack.")
                        type_writer_effect("2) Sacrifice yourself to defeat Radiel and protect everyone.")
                        garch2 = QuestionHandler.question_response("what will you do? : ","1","2")
                        if garch2 == "1":
                          type_writer_effect(" ")    
                          type_writer_effect("You gather all of your power to attack.")
                          type_writer_effect("The other angels give you their powers.")
                          type_writer_effect("You use that power to attack Radiel.")
                          type_writer_effect("Radiel falls down.")
                          type_writer_effect(" ")
                          type_writer_effect("Radiel: Maybe I shouldn't have fallen to the temptations of The darkness.")
                          type_writer_effect("Radiel dies.")
                          type_writer_effect("You have protected the Universe!!!")
                          type_writer_effect("Congragulations!!!")
                          type_writer_effect(" ")
                          type_writer_effect(" ")
                          type_writer_effect("THE END!!!.")

                        elif garch2 == "2":
                          type_writer_effect(" ")
                          type_writer_effect("You charge at Radiel and try to divert the dircetion of his attack away from the other angels.")
                          type_writer_effect("You succeed.")
                          type_writer_effect("The effect of the attack kills Radiel!!")
                          type_writer_effect("But, You also die because you were near the attack!!!")
                          type_writer_effect("You defeated Radiel and protected the universe, but it costed you your life.")
                          type_writer_effect("You will be remmembered as a hero who saved the universe.")
                          type_writer_effect(" ")
                          type_writer_effect(" ")
                          type_writer_effect("THE END!!!.")
                      elif garch == "2":
                        type_writer_effect(" ")
                        type_writer_effect("You used your powers and started to purify Radiel.")
                        type_writer_effect("His attack reaches you, and you get heavily injured.")
                        type_writer_effect("Your skin starts to peel off, revealing your flesh beneath.")
                        type_writer_effect("The dark energy mixed with air suffocates you.")
                        type_writer_effect("You scream in pain while hearing Radiel's twisted laugh.")
                        type_writer_effect("You: I-I'm sorr ryy everyone...")
                        type_writer_effect("You: I'm sorry I cou-ldn't save yo-uu...")
                        type_writer_effect("You died.")
                        type_writer_effect(" ")
                        type_writer_effect("Game Over")

        elif fsm == "2":
                type_writer_effect("You use your magic to fight Decalius.")
                type_writer_effect("Decalius has an anti magic armor, your attack failed.")
                type_writer_effect("Decalius attacks you, he splits you into two parts.")
                type_writer_effect("You died.")
                type_writer_effect(" ")
                type_writer_effect("Game Over ")

    elif sof == "2":
      type_writer_effect(" ")
      type_writer_effect("You try to fight the minions but you lose!!")
      type_writer_effect("The monsters paralyze you and start laying their eggs inside you.")
      type_writer_effect("After a long time, the eggs hatch.")
      type_writer_effect("The baby monsters start to eat you from the inside while You are alive.")
      type_writer_effect("You scream in pain until you die.")
      type_writer_effect("Fighting monster without any weapons or powers, what a genius!!")
      type_writer_effect("Game Over.")


  elif response == "2": 
    type_writer_effect("WHAT A PATHETIC COWARD!!!, You said you are not barve enough to protect the realms!")
    type_writer_effect("But you can't escape your destiny, You are still going to protect the realms.")
    type_writer_effect("So go on, little coward, play your part in this grand charade.")
    type_writer_effect("The realms may tremble, but they'll tremble even more at the thought of being defended by someone as spineless as you!")
    type_writer_effect("....")
    type_writer_effect("Anyway.")
    type_writer_effect(" ")
    type_writer_effect("You are in the celestial realm, doing your usual routine.")
    type_writer_effect("Suddenly, The universe shows you visions of the future about an incoming war.")
    type_writer_effect(" ")
    type_writer_effect("You: I have to do something to stop this war!. what should I do?")
    type_writer_effect(" ")
    type_writer_effect("1) Seek help from your friend.")
    type_writer_effect("2) Visit the library of heavens.")
    fv = QuestionHandler.question_response("Enter your choice: ","1","2")
    if fv == "1":
      type_writer_effect(" ")
      type_writer_effect("You go to look for your friend, Aurellius.")
      type_writer_effect("You enter Aurellius house, and you find him dead on the floor.")
      type_writer_effect(" ")
      type_writer_effect("You look around the house to find a clue, and you find a note from Aurellius.")
      type_writer_effect("You discover that the archangel Radiel has fallen to the darkness and became evil.")
      type_writer_effect("Radiel has used dark magic to control other angels and is planning to sacrifice a lot of creatures to ascend to godhood and control the universe.")
      type_writer_effect(" ")
      type_writer_effect("You go to fight Radiel and stop his evil plans")
      type_writer_effect(" ")
      type_writer_effect("On your way, you face hundreds of radiel minions")

      type_writer_effect("1) Fight them.")
      type_writer_effect("2) Run Away.")
      minfr = QuestionHandler.question_response("Enter your choice: ","1","2")
      if minfr == "1":
        type_writer_effect(" ")
        type_writer_effect("You fight the minions and defeat them, but you have been heavily injured.")
        type_writer_effect("Radiel shows up!!")
        type_writer_effect("You: I guess even the most righteous angels can't escape temptations")
        type_writer_effect("You: So, will you kill me now?.")
        type_writer_effect("Radiel: You are too powerful for me too control, so killing you is my only option.")
        type_writer_effect("Radiel attacks, but before you die, the universe casts some unkown magic on you.")
        type_writer_effect("Radiel cuts your head, You died")
        type_writer_effect(".....")
        type_writer_effect("But maybe that wasn't the end?")
      elif minfr == "2":
        type_writer_effect(" ")
        type_writer_effect("You run away from the minions, But eventually they catch up to you!.")
        type_writer_effect(" ")
        type_writer_effect("You fight the minions and defeat them, but you have been heavily injured.")
        type_writer_effect("Radiel shows up!!")
        type_writer_effect("You: I guess even the most righteous angels can't escape temptations")
        type_writer_effect("You: So, will you kill me now?.")
        type_writer_effect("Radiel: You are too powerful for me too control, so killing you is my only option.")
        type_writer_effect("Radiel attacks, but before you die, the universe casts some unkown magic on you.")
        type_writer_effect("Radiel cuts your head, You died")
        type_writer_effect(".....")
        type_writer_effect("But maybe that wasn't the end?")
    elif fv == "2":
      type_writer_effect(" ")
      type_writer_effect("You go to the library of heavens and search for a clue.")
      type_writer_effect("You didn't find anything in the library, so you go to ask for help from your friend.")
      type_writer_effect(" ")
      type_writer_effect("You go to look for your friend, Aurellius.")
      type_writer_effect("You enter Aurellius house, and you find him dead on the floor.")
      type_writer_effect(" ")
      type_writer_effect("You look around the house to find a clue, and you find a note from Aurellius.")
      type_writer_effect("You discover that the archangel Radiel has fallen to the darkness and became evil.")
      type_writer_effect("Radiel has used dark magic to control other angels and is planning to sacrifice a lot of creatures to ascend to godhood and control the universe.")
      type_writer_effect(" ")
      type_writer_effect("You go to fight Radiel and stop his evil plans")
      type_writer_effect(" ")
      type_writer_effect("On your way, you face hundreds of radiel minions")

      type_writer_effect("1) Fight them.")
      type_writer_effect("2) Run Away.")
      minfr = QuestionHandler.question_response("Enter your choice: ","1","2")
      if minfr == "1":
        type_writer_effect(" ")
        type_writer_effect("You fight the minions and defeat them, but you have been heavily injured.")
        type_writer_effect("Radiel shows up!!")
        type_writer_effect("You: I guess even the most righteous angels can't escape temptations")
        type_writer_effect("You: So, will you kill me now?.")
        type_writer_effect("Radiel: You are too powerful for me too control, so killing you is my only option.")
        type_writer_effect("Radiel attacks, but before you die, the universe casts some unkown magic on you.")
        type_writer_effect("Radiel cuts your head, You died")
        type_writer_effect(".....")
        type_writer_effect("But maybe that wasn't the end?")
      elif minfr == "2":
        type_writer_effect(" ")
        type_writer_effect("You run away from the minions, But eventually they catch up to you!.")
        type_writer_effect(" ")
        type_writer_effect("You fight the minions and defeat them, but you have been heavily injured.")
        type_writer_effect("Radiel shows up!!")
        type_writer_effect("You: I guess even the most righteous angels can't escape temptations")
        type_writer_effect("You: So, will you kill me now?.")
        type_writer_effect("Radiel: You are too powerful for me too control, so killing you is my only option.")
        type_writer_effect("Radiel attacks, but before you die, the universe casts some unkown magic on you.")
        type_writer_effect("Radiel cuts your head, You died")
        type_writer_effect(".....")
        type_writer_effect("But maybe that wasn't the end?")

    type_writer_effect(" ")
    type_writer_effect(" ")
    type_writer_effect("You open your eyes, and realize you have reincarnated into a human body!")
    type_writer_effect("You: I guess that was the magic of the universe!")
    type_writer_effect("You are imprisoned in a cursed castle that is filled with monsters and ruled by lich.")
    type_writer_effect("You can feel that your angelic power is in the castle, there are 4 fragments.")
    type_writer_effect("You manage to escape from the prsion and go to find the fragments.")
    type_writer_effect("On your way to collect the fragments, you face some insect monsters.")
    type_writer_effect(" ")
    type_writer_effect("1) Sneak around them")
    type_writer_effect("2) Fight them")
    type_writer_effect(" ")
    sof = QuestionHandler.question_response("what will you do? : ","1","2")

    if sof == "1":
      type_writer_effect(" ")
      type_writer_effect("The minions were busy eating someone, and they didn't notice you.")
      type_writer_effect("You suceed in sneaking around them.")
      type_writer_effect(" ")
      type_writer_effect("You go looking for the fragments of your angelic power")
      type_writer_effect("You see a monster, but it hasn't noticed you.")
      type_writer_effect(" ")
      type_writer_effect("1) Fight it")
      type_writer_effect("2) Sneak around it")
      fos = QuestionHandler.question_response("what will you do? : ","1","2")

      if fos == "1":
        type_writer_effect(" ")
        type_writer_effect("You fight the monster, but you lose.")
        type_writer_effect("The monster starts to tear you piece by piece.")
        type_writer_effect("When you are on the verge of death, the monster lights you on fire.")
        type_writer_effect("You scream in pain as you are burning slowly till you die")
        type_writer_effect("You were unarmed, what did you expect?")
        type_writer_effect("Game Over.")

      elif fos == "2":
        type_writer_effect(" ")
        type_writer_effect("You sneak aroud the monster succesfully.")
        type_writer_effect("That was a smart decesion, after all you were unarmed.")
        type_writer_effect(" ")
        type_writer_effect("you continue on your way until you find The fragment, it's inside a sword")
        type_writer_effect("You pick the sword, but to restore your powers, you have to collect the other fragments.")
        type_writer_effect("The fragment inside the sword allows you to use some magic.")
        type_writer_effect("Untill you restore your power, you You can use the sword to fight and cast magic.")
        type_writer_effect("You leave the room to continue your journey.")
        type_writer_effect("On your way out, you encounter a monster.")
        type_writer_effect(" ")
        type_writer_effect("1) Fight it")
        type_writer_effect("2) Run away")
        type_writer_effect(" ")
        rof = QuestionHandler.question_response("what will you do? : ","1","2")

        if rof == "1":
          type_writer_effect("You fight the monster and kill it")
          type_writer_effect("You notice that the monster was holding something.")
          type_writer_effect("You: What's that?.")
          type_writer_effect("You pick it up")
          type_writer_effect("It's a bitten human hand")
          type_writer_effect("You: ....., eww!")
          type_writer_effect("You throw it on the ground.")

        elif rof == "2":
            type_writer_effect(" ")
            type_writer_effect("You run away from the monster and move on your way.")
            type_writer_effect("Like the pathetic coward you are, you didn't fight the monster.")
        type_writer_effect(" ")
        type_writer_effect("While you are walking, you hear someone screaming.")
        type_writer_effect(" ")
        type_writer_effect("You: What was that?!")
        type_writer_effect("You: Let me go and check.")
        type_writer_effect("You see a girl surrounded by monsters. What will you do?")
        type_writer_effect(" ")
        type_writer_effect("1) Help her")
        type_writer_effect("2) Move on your way!")
        hom = QuestionHandler.question_response("what will you do? : ","1","2")
        if hom == "1":
            type_writer_effect("You defeat the monsters and save the girl.")
            type_writer_effect("Girl: Thank you so much!") 
            type_writer_effect("Girl: I have to go now, but let me advice you this.")
            type_writer_effect(" There is a monster called Decalius, he has an anti magic armour, so magic doesn't affect him.")

        elif hom == "2":
          type_writer_effect("You: That's not my problem.")
          type_writer_effect("You didn't help her because you are a coward")
          type_writer_effect(" ")
          type_writer_effect("You continue on your way.")
        type_writer_effect(" ")
        type_writer_effect("As you move towards the fragment, you encounter Decalius, the Knight of Unhallowed Blood!!!")
        type_writer_effect("You enter the fight.")
        type_writer_effect(" ")
        type_writer_effect("1) Fight using your sword.")
        type_writer_effect("2) Fight using your magic.")
        fsm = QuestionHandler.question_response("what will you do? : ","1","2")
        if fsm == "1":
            type_writer_effect("")
            type_writer_effect("You attack decalius with your sword.")
            type_writer_effect("You defeat Decalius, and you take his anti magic armor.")
            type_writer_effect("You continue on your way.")
            type_writer_effect("You reach the place of the second fragment, and you encounter Eurika, the ghost of Black blood!!")
            type_writer_effect("Defeat Eurika to take the fragment")
            type_writer_effect(" ")
            type_writer_effect("1) Fight using your sword.")
            type_writer_effect("2) Fight using your magic.")       
            eur = QuestionHandler.question_response("what will you do? : ","1","2")
            if eur == "1":
              type_writer_effect(" ")
              type_writer_effect("You attack Eurika with your sword, your attack passes through her body.")
              type_writer_effect("Eurika attacks with magic, but she fails because of your armour.")
              type_writer_effect("Eurika screams loudly, you start bleading from your ears.")
              type_writer_effect("You died.")
              type_writer_effect("How stupid do you have to be to fight a ghost using a sword?")
              type_writer_effect(" ")
              type_writer_effect("Game Over.")
            elif eur == "2":
              type_writer_effect(" ")
              type_writer_effect("You attack Eurika with your magic.")
              type_writer_effect("You defeated Eurika, and got the second fragment.")
              type_writer_effect("The last two fragments are in the lich's room, so you go there.")
              type_writer_effect("You enter the lich's room, but the lich is not there.")
              type_writer_effect("You see a wierd ring on a table inside the room.")
              type_writer_effect("If you wear it, you will gain dark magic, but that can be dangerous")
              type_writer_effect(" ")
              type_writer_effect("1) Wear the ring.")
              type_writer_effect("2) destroy the ring.")
              gob = QuestionHandler.question_response("what will you do? : ","1","2")
              if gob == "1":
                  type_writer_effect("You pick up the ring.")
                  type_writer_effect("You gain Dark magic, But you have been corrupted")
                  type_writer_effect("The lich notices your magic, and attacks you with his magic.")
                  type_writer_effect(" ")
                  type_writer_effect("1) Defend using your magic.")
                  type_writer_effect("2) Charge at him and attack.")
                  flich = QuestionHandler.question_response("what will you do? : ","1","2")
                  if flich == "1":
                    type_writer_effect(" ") 
                    type_writer_effect("You use magic to bounce his attack, you succeed.")
                    type_writer_effect("The lich uses magic to throw stone at you.")
                    type_writer_effect("You died, crushed by stones.")
                    type_writer_effect("Like a little pathetic bug.")
                    type_writer_effect(" ")
                    type_writer_effect("Game Over.")
                  elif flich == "2":
                      type_writer_effect(" ")
                      type_writer_effect("You charge at the lich, his magic fails because of your armour.")
                      type_writer_effect("Your attack succeed.")
                      type_writer_effect(" ")
                      type_writer_effect("The lich is still affected by your attack, you have chance to send a final attack.")
                      type_writer_effect("The lich is too strong, you have to sacrifice something to activate a powerful magic to kill him.")
                      type_writer_effect(" ")
                      type_writer_effect("1) sacrifice the prisoners to attack.")
                      type_writer_effect("2) sacrifice Your dark magic to attack.")
                      flich2 = QuestionHandler.question_response("what will you do? : ","1","2")
                      type_writer_effect(" ")
                      if flich2 == "1":
                        type_writer_effect(" ")
                        type_writer_effect("You sacrifice prisoners to activate a powerful dark magic.")
                        type_writer_effect("Your attacks succeed, the lich dies.")
                        type_writer_effect("You defeated the lich, but the dark magic inside grew stronger and made you evil.")
                        type_writer_effect(".........")
                        type_writer_effect("You collect the other two fragments and try to restore your power.")
                        type_writer_effect("Your powers rejects you because you became evil.")
                        type_writer_effect("You are unable to restore your power and ascend celestial.")
                        type_writer_effect("You use your dark magic to ascend to the celestial realm.")
                        type_writer_effect("You can't take your equipment with you.")

                        type_writer_effect(" ")
                        type_writer_effect(" ")
                        type_writer_effect("You are now in the celestial realm.")
                        type_writer_effect("You are heading towards the archangel to defeat him")
                        type_writer_effect("But Your goal has changed?!!.")
                        type_writer_effect(" ")
                        type_writer_effect("On your way, You encounter some mindcontrolled angels.")
                        type_writer_effect(" ")
                        type_writer_effect("1) Convince them to join your side.")
                        type_writer_effect("2) Use your dark magic to control them.")
                        darka = QuestionHandler.question_response("what will you do? : ","1","2")
                        if darka == "1":
                          type_writer_effect(" ")
                          type_writer_effect("You: Join my side and fight Radiel with me.")
                          type_writer_effect("Angels: Why should we join you?")
                          type_writer_effect("You convince them to join your side, by promising to give them power.")
                          type_writer_effect("The angels pretend to join your side.")
                          type_writer_effect("But after a while, They attack you from behind!!")
                          type_writer_effect("They kept on stabing you until you died.")
                          type_writer_effect("they were still being controlled by Radiel.")
                          type_writer_effect("And you believed they were on your side!!")
                          type_writer_effect("What an idiot, easily manipulated, pathetic pawn.")
                          type_writer_effect(" ")
                          type_writer_effect("Game Over.")
                        elif darka == "2":
                          type_writer_effect(" ")
                          type_writer_effect("You use your dark magic to control them.")
                          type_writer_effect("The angels will obey you instead of radiel.")
                          type_writer_effect(" ")
                          type_writer_effect("You move towards Radiel, and on Your way you control other angels.")
                          type_writer_effect(" ")
                          type_writer_effect("After a while, You reached Radiel.")
                          type_writer_effect("Radiel: Guess you we are not that different after all.")
                          type_writer_effect("You: The only difference between us is that I will win and you will die.")
                          type_writer_effect("Radiel attacks you with dark energy")
                          type_writer_effect(" ")
                          type_writer_effect("1) Absorb the dark energy.")
                          type_writer_effect("2)Reflect his attack.")

                          darch = QuestionHandler.question_response("what will you do? : ","1","2")
                          if darch == "1":
                            type_writer_effect(" ")
                            type_writer_effect("You try to absorb the dark energy, but you fail.")
                            type_writer_effect("You get heavily injured.")
                            type_writer_effect("Radiel attacks you again.")
                            type_writer_effect("You have fallen down and are unable to move!!")
                            type_writer_effect("Radiel attacks you, he stabs you in the eyes.")
                            type_writer_effect("You scream in pain while Radiel is laughing at you.")
                            type_writer_effect("You die.")
                            type_writer_effect(" ")
                            type_writer_effect("Game Over.")

                          elif darch == "2":
                            type_writer_effect(" ")
                            type_writer_effect("You use you magic to reflect the dark energy, you succeed")
                            type_writer_effect("You attack Radiel and fight him for a while.")
                            type_writer_effect("Radiel gets injured, so he starts to perform his final attack.")
                            type_writer_effect(" ")
                            type_writer_effect("You have two choices.")
                            type_writer_effect("1) Use both of your dark magic and angelic powers to attack him.")
                            type_writer_effect("2) Sacrifice nearby angels to activate a powerful dark magic.")
                            darch2d = QuestionHandler.question_response("what will you do? : ","1","2")
                            if darch2d == "1":
                              type_writer_effect(" ")
                              type_writer_effect(" You mix your dark magic with your angelic powers to attack Radiel.")
                              type_writer_effect("Your attack is more powerful than Radiel's attack.")
                              type_writer_effect("You defeat Radiel.")
                              type_writer_effect(" ")
                              type_writer_effect(".....")     
                              type_writer_effect("But mixing two opposite powers was a bad idea.")
                              type_writer_effect("You: What's happeneing?")
                              type_writer_effect("The dark magic and Your angelic powers are too powerful, They are fighting inside of you.")
                              type_writer_effect("Unable to handle these powers, You start to feel agonizing pain.")
                              type_writer_effect("You body is being torn from the inside as you scream in pain.")
                              type_writer_effect("As your consciousness is fading, You wonder if have lost yourself in your journey.")
                              type_writer_effect("You: ...D-Did I....")
                              type_writer_effect("You: Did I choose the wrong path?")
                              type_writer_effect(".......")
                              type_writer_effect("You died.")
                              type_writer_effect(" ")
                              type_writer_effect(" ")
                              type_writer_effect("THE END.")

                            elif darch2d == "2":
                              type_writer_effect(" ")
                              type_writer_effect("You sarifice nearby angels to activite a powerful dark magic.")
                              type_writer_effect("Your attacks succeed, Radiel falls down.")
                              type_writer_effect("You absorb Radiel's power while he screams in agony.")
                              type_writer_effect("Radiel dies!")
                              type_writer_effect(" ")
                              type_writer_effect("Instead of protecting the realms, you use your dark magic to ascend to godhood!!")
                              type_writer_effect("You win in the end, but you have lost yourself to the darkness.")
                              type_writer_effect(" ")
                              type_writer_effect(" ")
                              type_writer_effect("THE END.")


                      elif flich2 == "2":
                        type_writer_effect(" ")
                        type_writer_effect("You sacrifice your dark magic to activate a powerful spell")
                        type_writer_effect("Your attacks succeed, the lich dies.")
                        type_writer_effect(" ")
                        type_writer_effect("You collect all the fragments and restore your angelic powers")
                        type_writer_effect(" ")
                        type_writer_effect(" ")
                        type_writer_effect("You ascend to the celestial realm.")
                        type_writer_effect("To fight Radiel and his followers, the universe gives you the power to purify the evil.")
                        type_writer_effect("Now, you can bring the corrupted angels back to their nature.")
                        type_writer_effect("But, you have to weaken them first.")
                        type_writer_effect(" ")
                        type_writer_effect("You move toward Radiel.")
                        type_writer_effect("On your way, you face corrupted angels")
                        type_writer_effect(" ")
                        type_writer_effect("1) Offer to help them and purify the dark in them.")
                        type_writer_effect("2) Fight them, then purify them.")

                        gway = QuestionHandler.question_response("what will you do? : ","1","2")
                        if gway == "1":
                          type_writer_effect(" ")
                          type_writer_effect("They accept your offer.")
                          type_writer_effect("You start to purify them.")
                          type_writer_effect("But they take this chance to attack and stabbed you.")
                          type_writer_effect("They watched you as you bled slowly to your death.")
                          type_writer_effect("You died.")
                          type_writer_effect(" ")
                          type_writer_effect("Game Over.")
                        elif gway == "2":
                          type_writer_effect(" ")
                          type_writer_effect("You fight them and win.")
                          type_writer_effect("You start to purify them.")
                          type_writer_effect("They are purified, and they will join your side.")
                          type_writer_effect(" ")
                          type_writer_effect("On your way to Radiel, you purify other angels.")
                          type_writer_effect(" ")
                          type_writer_effect("You reach Radiel.")
                          type_writer_effect(" ")
                          type_writer_effect("Radiel: LOOK AT YOU, back from the dead!!!")
                          type_writer_effect("You: I wish I could save you, but you reached the point of no return.")
                          type_writer_effect("You: it's your turn to die now.")
                          type_writer_effect(" ")
                          type_writer_effect("Radiel attacks you using dark energy.")
                          type_writer_effect(" ")
                          type_writer_effect("1) Defend the attack with the other angels.")
                          type_writer_effect("2) Use your powers to purify Radiel.")
                          garch = QuestionHandler.question_response("what will you do? : ","1","2")
                          if garch == "1":
                            type_writer_effect(" ")
                            type_writer_effect("You succeed in defending the attack.")
                            type_writer_effect("After a fierce battle, Radiel uses his final attack to kill you and the angels!!")
                            type_writer_effect(" ")
                            type_writer_effect("1) Perform a combined attack.")
                            type_writer_effect("2) Sacrifice yourself to defeat Radiel and protect everyone.")
                            garch2 = QuestionHandler.question_response("what will you do? : ","1","2")
                            if garch2 == "1":
                              type_writer_effect(" ")    
                              type_writer_effect("You gather all of your power to attack.")
                              type_writer_effect("The other angels give you their powers.")
                              type_writer_effect("You use that power to attack Radiel.")
                              type_writer_effect("Radiel falls down.")
                              type_writer_effect(" ")
                              type_writer_effect("Radiel: Maybe I shouldn't have fallen to the temptations of The darkness.")
                              type_writer_effect("Radiel dies.")
                              type_writer_effect("You have protected the Universe!!!")
                              type_writer_effect("Congragulations!!!")
                              type_writer_effect(" ")
                              type_writer_effect(" ")
                              type_writer_effect("THE END!!!.")

                            elif garch2 == "2":
                              type_writer_effect(" ")
                              type_writer_effect("You charge at Radiel and try to divert the dircetion of his attack away from the other angels.")
                              type_writer_effect("You succeed.")
                              type_writer_effect("The effect of the attack kills Radiel!!")
                              type_writer_effect("But, You also die because you were near the attack!!!")
                              type_writer_effect("You defeated Radiel and protected the universe, but it costed you your life.")
                              type_writer_effect("You will be remmembered as a hero who saved the universe.")
                              type_writer_effect(" ")
                              type_writer_effect(" ")
                              type_writer_effect("THE END!!!.")


              elif gob == "2":
                  type_writer_effect("You destroy the ring by throwing it into the lava.")
                  type_writer_effect("You look around and you find the lich, he hasn't noticed you yet.")
                  type_writer_effect(" ")
                  type_writer_effect("1) Attack him.")
                  type_writer_effect("2) search for the other fragment to become stronger.")
                  nrlich = QuestionHandler.question_response("what will you do? : ","1","2")
                  if nrlich == "1":
                    type_writer_effect(" ")
                    type_writer_effect("You attack the lich, and succeed.")
                    type_writer_effect("Before you do anything else, the lich minions attack you")
                    type_writer_effect("They pierce you with their spears until you die.")
                    type_writer_effect(" ")
                    type_writer_effect("Game Over.")
                  elif nrlich == "2":
                    type_writer_effect(" ")
                    type_writer_effect("You find the other fragment, your magic is stronger now.")
                    type_writer_effect("The lich notices you and attacks you.")
                    type_writer_effect(" ")
                    type_writer_effect("1) Dodge his attack, and prepare your attack.")
                    type_writer_effect("2) Charge at the lich and attack him.")
                    nrlich2 = QuestionHandler.question_response("what will you do? : ","1","2")
                    if nrlich2 == "1":
                      type_writer_effect(" ")
                      type_writer_effect("You dodge the lich attack, and prepare your attack.")
                      type_writer_effect("But before you are done, the lich attacks you again and pushes you into the lava pool.")
                      type_writer_effect("You died while burning slowly.")
                      type_writer_effect(" ")
                      type_writer_effect("Game Over.")
                    elif nrlich2 == "2":
                      type_writer_effect(" ")
                      type_writer_effect("the lich uses his magic to attack, but fails because of your armour.")
                      type_writer_effect("You charge at him and attack again, you succeed.")
                      type_writer_effect("The lich Dies.")
                      type_writer_effect(" ")
                      type_writer_effect("You collect all the fragments and restore your angelic powers")
                      type_writer_effect(" ")
                      type_writer_effect(" ")
                      type_writer_effect("You ascend to the celestial realm.")
                      type_writer_effect("To fight Radiel and his followers, the universe gives you the power to purify the evil.")
                      type_writer_effect("Now, you can bring the corrupted angels back to their nature.")
                      type_writer_effect("But, you have to weaken them first.")
                      type_writer_effect(" ")
                      type_writer_effect("You move toward Radiel.")
                      type_writer_effect("On your way, you face corrupted angels")
                      type_writer_effect(" ")
                      type_writer_effect("1) Offer to help them and purify the dark in them.")
                      type_writer_effect("2) Fight them, then purify them.")

                      gway = QuestionHandler.question_response("what will you do? : ","1","2")
                      if gway == "1":
                        type_writer_effect(" ")
                        type_writer_effect("They accept your offer.")
                        type_writer_effect("You start to purify them.")
                        type_writer_effect("But they take this chance to attack and stabbed you.")
                        type_writer_effect("They watched you as you bled slowly to your death.")
                        type_writer_effect("You died.")
                        type_writer_effect(" ")
                        type_writer_effect("Game Over.")
                      elif gway == "2":
                        type_writer_effect(" ")
                        type_writer_effect("You fight them and win.")
                        type_writer_effect("You start to purify them.")
                        type_writer_effect("They are purified, and they will join your side.")
                        type_writer_effect(" ")
                        type_writer_effect("On your way to Radiel, you purify other angels.")
                        type_writer_effect(" ")
                        type_writer_effect("You reach Radiel.")
                        type_writer_effect(" ")
                        type_writer_effect("Radiel: LOOK AT YOU, back from the dead!!!")
                        type_writer_effect("You: I wish I could save you, but you reached the point of no return.")
                        type_writer_effect("You: it's your turn to die now.")
                        type_writer_effect(" ")
                        type_writer_effect("Radiel attacks you using dark energy.")
                        type_writer_effect(" ")
                        type_writer_effect("1) Defend the attack with the other angels.")
                        type_writer_effect("2) Use your powers to purify Radiel.")
                        garch = QuestionHandler.question_response("what will you do? : ","1","2")
                        if garch == "1":
                          type_writer_effect(" ")
                          type_writer_effect("You succeed in defending the attack.")
                          type_writer_effect("After a fierce battle, Radiel uses his final attack to kill you and the angels!!")
                          type_writer_effect(" ")
                          type_writer_effect("1) Perform a combined attack.")
                          type_writer_effect("2) Sacrifice yourself to defeat Radiel and protect everyone.")
                          garch2 = QuestionHandler.question_response("what will you do? : ","1","2")
                          if garch2 == "1":
                            type_writer_effect(" ")    
                            type_writer_effect("You gather all of your power to attack.")
                            type_writer_effect("The other angels give you their powers.")
                            type_writer_effect("You use that power to attack Radiel.")
                            type_writer_effect("Radiel falls down.")
                            type_writer_effect(" ")
                            type_writer_effect("Radiel: Maybe I shouldn't have fallen to the temptations of The darkness.")
                            type_writer_effect("Radiel dies.")
                            type_writer_effect("You have protected the Universe!!!")
                            type_writer_effect("Congragulations!!!")
                            type_writer_effect(" ")
                            type_writer_effect(" ")
                            type_writer_effect("THE END!!!.")

                          elif garch2 == "2":
                            type_writer_effect(" ")
                            type_writer_effect("You charge at Radiel and try to divert the dircetion of his attack away from the other angels.")
                            type_writer_effect("You succeed.")
                            type_writer_effect("The effect of the attack kills Radiel!!")
                            type_writer_effect("But, You also die because you were near the attack!!!")
                            type_writer_effect("You defeated Radiel and protected the universe, but it costed you your life.")
                            type_writer_effect("You will be remmembered as a hero who saved the universe.")
                            type_writer_effect(" ")
                            type_writer_effect(" ")
                            type_writer_effect("THE END!!!.")
                        elif garch == "2":
                          type_writer_effect(" ")
                          type_writer_effect("You used your powers and started to purify Radiel.")
                          type_writer_effect("His attack reaches you, and you get heavily injured.")
                          type_writer_effect("Your skin starts to peel off, revealing your flesh beneath.")
                          type_writer_effect("The dark energy mixed with air suffocates you.")
                          type_writer_effect("You scream in pain while hearing Radiel's twisted laugh.")
                          type_writer_effect("You: I-I'm sorr ryy everyone...")
                          type_writer_effect("You: I'm sorry I cou-ldn't save yo-uu...")
                          type_writer_effect("You died.")
                          type_writer_effect(" ")
                          type_writer_effect("Game Over")

        elif fsm == "2":
          type_writer_effect("You use your magic to fight Decalius.")
          type_writer_effect("Decalius has an anti magic armor, your attack failed.")
          type_writer_effect("Decalius attacks you, he splits you into two parts.")
          type_writer_effect("You died.")
          type_writer_effect(" ")
          type_writer_effect("Game Over ")

      elif sof == "2":
        type_writer_effect(" ")
        type_writer_effect("You try to fight the minions but you lose!!")
        type_writer_effect("The monsters paralyze you and start laying their eggs inside you.")
        type_writer_effect("After a long time, the eggs hatch.")
        type_writer_effect("The baby monsters start to eat you from the inside while You are alive.")
        type_writer_effect("You scream in pain until you die.")
        type_writer_effect(" ")
        type_writer_effect("Fighting monster without any weapons or powers, what a genius!!")
        type_writer_effect(" ")
        type_writer_effect("Game Over.")

if __name__ == '__main__':
  throne()